"""add_match_notification_flags

Revision ID: 4d0c715aee9e
Revises: b8bee1a2b3c4
Create Date: 2026-04-21 19:50:32.051590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0c715aee9e'
down_revision: Union[str, Sequence[str], None] = 'b8bee1a2b3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('notified_30m', sa.Boolean(), nullable=True))
    op.add_column('matches', sa.Column('notified_5m', sa.Boolean(), nullable=True))
    op.add_column('matches', sa.Column('notified_0m', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'notified_0m')
    op.drop_column('matches', 'notified_5m')
    op.drop_column('matches', 'notified_30m')
    # ### end Alembic commands ###
