"""add_match_indexes

Revision ID: b8bee1a2b3c4
Revises: a77ecf351dc1
Create Date: 2026-04-21 14:47:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8bee1a2b3c4'
down_revision: Union[str, Sequence[str], None] = 'a77ecf351dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_start_time'), 'matches', ['start_time'], unique=False)
    op.create_index(op.f('ix_matches_home_team_code'), 'matches', ['home_team_code'], unique=False)
    op.create_index(op.f('ix_matches_away_team_code'), 'matches', ['away_team_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_away_team_code'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_code'), table_name='matches')
    op.drop_index(op.f('ix_matches_start_time'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    # ### end Alembic commands ###
